# Q1    a.

In [2]:
import numpy as np

In [2]:
arr=[1,2,3,6,4,10]

In [3]:
reversed_arr=arr[::-1]

In [4]:
reversed_arr

[10, 4, 6, 3, 2, 1]

# Q1 b.

In [6]:
a=np.array([[1,2,3],[2,4,5],[1,2,3]])

In [7]:
a.flatten()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

# Q1 c.

In [9]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])

In [10]:
arr1==arr2

array([[ True,  True],
       [ True,  True]])

# Q1 d. 

In [11]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])

In [16]:
unique_values, counts = np.unique(x, return_counts=True)
most_frequent_value = unique_values[np.argmax(counts)] 
print(most_frequent_value)


1


In [17]:
np.bincount(y).argmax()

1

In [19]:
np.where(np.bincount(y).argmax())

(array([0], dtype=int64),)

# Q1 e

In [20]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')

In [21]:
gfg

matrix([[ 4,  1,  9],
        [12,  3,  1],
        [ 4,  5,  6]])

In [22]:
np.sum(gfg)

45

In [23]:
np.sum(gfg,axis=1)

matrix([[14],
        [16],
        [15]])

In [25]:
np.sum(gfg,axis=0)

matrix([[20,  9, 16]])

# Q1 f

In [27]:
n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])

In [28]:
np.sum(np.diag(n_array))

176

In [30]:
np.linalg.eig(n_array)

(array([98.16835147, 28.097044  , 49.73460452]),
 array([[ 0.4574917 ,  0.34637121, -0.15017693],
        [ 0.28447814, -0.72784061, -0.4852124 ],
        [ 0.84248058,  0.59184038,  0.8614034 ]]))

In [31]:
np.linalg.inv(n_array)

array([[ 0.02404141, -0.00911212, -0.00444671],
       [-0.01667882,  0.02966905,  0.0024785 ],
       [ 0.00631287, -0.01603732,  0.01217379]])

In [32]:
np.linalg.det(n_array)

137180.0000000001

# Q1 g.

In [33]:
p=[[1,2],[2,3]]
q=[[4,5],[6,7]]

In [39]:
np.matmul(p,q)

array([[16, 19],
       [26, 31]])

In [38]:
np.cov(p,q)

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

# Q1 h.

In [40]:
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])

In [41]:
np.inner(x,y)

array([[17, 52],
       [13, 62]])

In [42]:
np.outer(x,y)

array([[ 2, 10,  0, 10, 20,  6],
       [ 3, 15,  0, 15, 30,  9],
       [ 4, 20,  0, 20, 40, 12],
       [ 3, 15,  0, 15, 30,  9],
       [ 2, 10,  0, 10, 20,  6],
       [ 9, 45,  0, 45, 90, 27]])

In [44]:
A, B = np.meshgrid(x, y)

cartesian_product = np.stack((A.flatten(), B.flatten()), axis=1)

print(cartesian_product)

[[ 2  1]
 [ 3  1]
 [ 4  1]
 [ 3  1]
 [ 2  1]
 [ 9  1]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 3  0]
 [ 2  0]
 [ 9  0]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 3 10]
 [ 2 10]
 [ 9 10]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 3  3]
 [ 2  3]
 [ 9  3]]


# Q2 a.

In [43]:
array=np.array([[2,3,4],[-4,5,-6]])

In [45]:
np.absolute(array)

array([[2, 3, 4],
       [4, 5, 6]])

In [48]:
array.flatten()

array([ 2,  3,  4, -4,  5, -6])

In [53]:
np.percentile(array,25)


-2.5

In [51]:
np.percentile(array,50)


2.5

In [52]:
np.percentile(array,75)

3.75

In [54]:
np.mean(array.flatten())

0.6666666666666666

In [55]:
np.median(array.flatten())

2.5

In [57]:
from scipy import stats
stats.mode(array.flatten())

C:\Users\hp\AppData\Local\Temp\ipykernel_23100\3425854148.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(array.flatten())


ModeResult(mode=array([-6]), count=array([1]))

In [58]:
np.std(array)

4.149966532662911

# Q2 b.

In [59]:
a=np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])

In [61]:
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  3.])

In [62]:
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  3.])

In [63]:
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  3.])

In [64]:
np.round(a)

array([-2., -2., -0.,  0.,  2.,  2.,  3.])

# Q3 a.

In [3]:
array=np.array([10,52,62,16,16,54,453])

In [4]:
np.sort(array)

array([ 10,  16,  16,  52,  54,  62, 453])

In [8]:
np.argsort(array)

array([0, 3, 4, 1, 5, 2, 6], dtype=int64)

In [6]:
sorted_array=np.sort(array)

In [7]:
sorted_array[:4]

array([10, 16, 16, 52])

In [13]:
sorted_array[-5:]

array([ 16,  52,  54,  62, 453])

# 3 b.

In [24]:
array=np.array([1,1.2,2.2,2.0,3.0,2])

In [17]:
array.astype(int)

array([1, 1, 2, 2, 3, 2])

In [18]:
array.astype(float)

array([1. , 1.2, 2.2, 2. , 3. , 2. ])

In [19]:
integer_elements = array[array == array.astype(int)]

In [20]:
integer_elements

array([1., 2., 3., 2.])

In [29]:
array[1].dtype

dtype('float64')

In [40]:
# function to import image and save it as text file
from PIL import Image
import numpy as np

def img_to_array(path):
    
    img = Image.open(path)
    
    
    if img.mode == 'L':  # Grayscale
        img_array = np.array(img)
        file_name = 'grayscale_image_array.txt'
    elif img.mode == 'RGB':  # RGB
        img_array = np.array(img)
        file_name = 'rgb_image_array.txt'
    else:
        raise ValueError("Unsupported image mode: only 'L' (grayscale) and 'RGB' are supported")
    
    
    if img.mode == 'L':
        np.savetxt(file_name, img_array, fmt='%d')
    else:
        np.savetxt(file_name, img_array.reshape(-1, img_array.shape[2]), fmt='%d,%d,%d')
    
    print(f"Image array saved as {file_name}")

img_to_array(r'C:\Users\hp\OneDrive\Documents\Pictures\hacker1.jpg')

Image array saved as rgb_image_array.txt


In [43]:
np.loadtxt('rgb_image_array.txt',dtype=object)

array(['21,10,14', '21,10,14', '21,10,14', ..., '21,11,12', '21,11,12',
       '21,11,12'], dtype=object)